### ISSUE TITLE
I love everything except the name

### ISSUE THREAD

**Issue by jdunne525** [rwasef1830/grepripper#1]
It's fast.  It works just like my favorite baregrep.  It's open source.  
The only downside is that the name sounds terribly unprofessional and that's the only thing stopping me from getting my coworkers using it.  I might even fork it just to change the name and share.

**Comment by rwasef1830** [comment]
I'm not that creative with names :-D if you have a better name idea do share

**Comment by jdunne525** [comment]
I forked it and gave it the "very creative" name "BGrep". Not amazing, but it did the job.

**Comment by rwasef1830** [comment]
I'll rename it to BGrep and properly rename the whole code base, no need for PR.

**Comment by rwasef1830** [comment]
I will do so once I figure out the easiest way to do this.
